services:
  backend:
    ports:
      - 8000:80
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
        - action: rebuild
          path: ./backend/pyproject.toml
    restart: unless-stopped
    command: sh -c "watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- uv run main.py"

  db:
    ports:
      - 5432:5432