"""Add is_active to user_account

Revision ID: 52796858cd54
Revises: 19b8b2217993
Create Date: 2025-06-18 22:42:44.402300

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "52796858cd54"
down_revision: Union[str, Sequence[str], None] = "19b8b2217993"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat", "content")
    op.add_column("user_account", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.create_index(
        op.f("ix_user_account_is_active"), "user_account", ["is_active"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_account_is_active"), table_name="user_account")
    op.drop_column("user_account", "is_active")
    op.add_column(
        "chat", sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
